{% set name = "lucid" %}
{% set version = "1.0.2" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 87404556913ea9daf96a9d2d4b0ca6ddf7edda3a1b94ea28064fc741467e7e8f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lucid = lucid.launcher:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - ophyd
    - pcdsutils >=0.14.0
    - pydm
    - pyqt =5
    - pyyaml
    - qtpy
    - typhos
    - happi

test:
  requires:
    - python {{ python_min }}
  imports:
    - lucid
  commands:
    - lucid --help

about:
  home: https://github.com/pcdshub/lucid
  dev_url: https://github.com/pcdshub/lucid
  summary: 'SLAC National Accelerator Laboratory: LCLS User Control and Interface Design'
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
