{% set name = "lucid" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 624d3bd7640757503a2c25064663c4c668ceb461be21f377d0fb427fc7f8ff93

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lucid = lucid.launcher:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fuzzywuzzy
    - ophyd
    - pydm
    - pyqt >=5
    - pyqtads
    - pyyaml
    - qtpy
    - typhos
    - happi

test:
  imports:
    - lucid
  commands:
    - lucid --help

about:
  home: https://github.com/pcdshub/lucid
  dev_url: https://github.com/pcdshub/lucid
  summary: 'SLAC National Accelerator Laboratory: LCLS User Control and Interface Design'
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
