{% set name = "lucid" %}
{% set version = "1.0.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bf3a2f9650a7bb7ac3df8449634c665f4b85187c599d45ce92f00f3a2b6e81ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lucid = lucid.launcher:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - ophyd
    - pcdsutils >=0.14.0
    - pydm
    - pyqt =5
    - pyyaml
    - qtpy
    - typhos
    - happi

test:
  requires:
    - python {{ python_min }}
  imports:
    - lucid
  commands:
    - lucid --help

about:
  home: https://github.com/pcdshub/lucid
  dev_url: https://github.com/pcdshub/lucid
  summary: 'SLAC National Accelerator Laboratory: LCLS User Control and Interface Design'
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
