{% set name = "lucid" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 320fd9563fda2c470e4fed810ed52a337f1aeb225202d298b5d3fefa8c7fe5cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lucid = lucid.launcher:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - fuzzywuzzy
    - ophyd
    - pcdsutils >=0.14.0
    - pydm
    - pyqt =5
    - pyqtads >=4
    - pyyaml
    - qtpy
    - typhos
    - happi

test:
  requires:
    - python {{ python_min }}
  imports:
    - lucid
  commands:
    - lucid --help

about:
  home: https://github.com/pcdshub/lucid
  dev_url: https://github.com/pcdshub/lucid
  summary: 'SLAC National Accelerator Laboratory: LCLS User Control and Interface Design'
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
