{% set name = "lucid" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 28f84558f2d9a18ff5a0b0fbe9ba1a0907c79515e78f851cb674309f13ecdad0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - lucid = lucid.launcher:main

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - fuzzywuzzy
    - ophyd
    - pcdsutils
    - pydm
    - pyqt >=5
    - pyqtads
    - pyyaml
    - qtpy
    - typhos
    - happi

test:
  imports:
    - lucid
  commands:
    - lucid --help

about:
  home: https://github.com/pcdshub/lucid
  dev_url: https://github.com/pcdshub/lucid
  summary: 'SLAC National Accelerator Laboratory: LCLS User Control and Interface Design'
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - klauer
    - tangkong
    - zllentz
